### ISSUE TITLE
No PPI table BHVY or BHWY

### ISSUE THREAD

**Issue by dykesk** [WISDEM/CommonSE#8]
PPI_tables.txt  does contain tables for the codes BHVY or BHWY but it doesnt look like the csm model in commonse is finding them; you can see this when you run wisdem/lcoe_csm_assembly.py or lcoe_csm_2015_assembly

**Comment by kilojoules** [comment]
I noticed that commonse didn't properly install the `static` folder, which contains the ppi tables. I fixed this in 3c23b834e3256bb50ffa76f03aee95237a3c1889. `lcoe_csm_2015_assembly.py` and `lcoe_se_assembly.py` both seem to work with this change. @dykesk was this about `static` not being properly installed?

**Comment by dykesk** [comment]
yes - this is now fixed
